### PR TITLE
✨ Feature - AI Analysis Server Complete

### LINKED ISSUE #1: [ Feature ] - Packet Analysis Server Using Django, AI
## 🛠️ Planned development features
Filter에서 받은 패킷을 분석하는 AI 서버

## 📝 check-lists
- [x] Django Setting
- [x] AI Serving
- [x] Http Connection

### PR DESCRIPTION
**Pull request by hyungjoon-son**
## Issue
You need to link it to the index specifying which issue you addressed.
- Resolves : #1 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.
- AI Server Complete

### CODE REVIEW

**Comment by kurtyoon** [comment]
LGTM :)

**Review by dlawjddn — COMMENTED** [review]
굿입니다

**Review by kurtyoon — COMMENTED** [review]
LGTM :)

**Review by nykoh2001 — COMMENTED** [review]
👍🏻

**Review by kurtyoon — APPROVED** [review]

**Review by dlawjddn — APPROVED** [review]

**Review by nykoh2001 — APPROVED** [review]

**Pull request merged**
