### PR TITLE
✨ Feature - Packet Filter Server

### PR DESCRIPTION
**Pull request by jjuuuunnii**
## Issue
You need to link it to the index specifying which issue you addressed.

- Resolves : #8 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.

- 도메인작성 
- api filter 로직 작성

### CODE REVIEW

**Comment by kurtyoon** [comment]
LGTM XD

**Review by kurtyoon — COMMENTED** [review]
LGTM :)

**Review by nykoh2001 — COMMENTED** [review]
👍🏻

**Review by hyungjoon-son — APPROVED** [review]
고생하셨습니다~~

**Comment by dlawjddn** [comment]
고생티비 하셨습니다~

**Review by kurtyoon — APPROVED** [review]

**Review by dlawjddn — APPROVED** [review]

**Pull request merged**
